### ISSUE TITLE
[feature request] Control&Info in compact representation

### ISSUE THREAD

**Issue by KottV** [noee/mcwsplasmoid#1]
Greetings!
Thank You for this plasmoid.
Are you planing to add control buttons and info string in compact representation? It would be very feature-full addon:)
I mean, like PlayBar2 plasmoid https://github.com/audoban/PlayBar2 or Media Controller Compact https://store.kde.org/p/998887/

For now I use my simple plasmoid that just types track-artist near your mcws.

**Comment by noee** [comment]
Yeah, that looks like a good idea.  Maybe compact just defaults to the current zone selected and I can make the whole compact visual optional.

I actually have an MPRIS2 add-on that makes any (and all) MediaCenter servers available to your desktop, that might be an option too.  Then you could use an MPRIS2 client of your choice.  I'll play with it a little bit, see what is most useful.

**Comment by noee** [comment]
Pushed to master Compact View option.  Needs some polish, I can't get the sizing/formatting right, but it handles the basics and tracks whichever Zone you select from the Full View.  Enable/disable via the options.

Of course, feedback welcomed.

**Comment by KottV** [comment]
Great!
I added
`layoutDirection: Qt.RightToLeft`
that helps with aligning

**Comment by KottV** [comment]
> I actually have an MPRIS2 add-on that makes any (and all) MediaCenter servers available to your desktop, that might be an option too. Then you could use an MPRIS2 client of your choice. I'll play with it a little bit, see what is most useful.

Can I see it too? :)

**Comment by noee** [comment]
The MPRIS2 tool is CLI-only and multi-threaded (C++), so it won't work as a qml plugin ATM.  Not sure if I'm going to do anything with it or not.

**Comment by noee** [comment]
v1.1 now has a nice panel view for your zones.  You can make the view small (normal) that will show roughly one zone info or you go wider (check options).  It's just basically a horizontally scrollable list of your zones. 

Clicking on any zone will bring up the Plasmoid popup with that zone selected.

**Comment by KottV** [comment]
Cool.
What do you think about right-aligned text?

original
![mcws_orig](https://user-images.githubusercontent.com/4686351/31811844-58cc3d08-b5c4-11e7-89a3-bfd3762a5a41.png)

my
![mcws_my](https://user-images.githubusercontent.com/4686351/31811855-63d1fb20-b5c4-11e7-9bf4-7e8be05a2236.png)

**Comment by noee** [comment]
I like it.  I'm working on some ideas to save some panel space too.

**Comment by KottV** [comment]
I played with alignment because track name didn't kept in place and jumps up or down during track switching:
![mc_trname](https://user-images.githubusercontent.com/4686351/32259297-326916f4-bf0b-11e7-8f89-8806a7c048d6.png)

Finally I found some parameters that fixes trackname and artistname:
[CompactView.patch.gz](https://github.com/noee/mcwsplasmoid/files/1433063/CompactView.patch.gz)

**Comment by noee** [comment]
I actually have a little better fix that involves using the base QtQuick Text element for the two fields.  Something is not quite right with the Plasma.Label when it repaints.
