### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by KottV** [noee/mcwsplasmoid#3]
Hi!

While You struggling with cpu eating and polling, I'm appealing you to look in this patch.
It does next things:

1. Turns on native font rendering.
2. Aligns view to right side.
3. Aligns  buttons and text fields vertically and makes them more readable, especially on tiny panels.
4. Adds flat buttons option.

![mcws_vanilla](https://user-images.githubusercontent.com/4686351/39193285-875b8c0e-481e-11e8-9e56-57e300858f44.png)
![mcws_my](https://user-images.githubusercontent.com/4686351/39193295-8ca97cde-481e-11e8-9d18-403d49db5cb7.png)

[flat_allign_render.patch.gz](https://github.com/noee/mcwsplasmoid/files/1943130/flat_allign_render.patch.gz)

**Comment by noee** [comment]
Looks good.  I think #3 and #4 are already in this next release I'm planning.

I can't seem to read this patch file.  Can you send it as a pull request or as a text?

**Comment by KottV** [comment]
>I can't seem to read this patch file. Can you send it as a pull request or as a text?

strange...
there late night now, so I'll try make pull request tomorrow, ok?

**Comment by noee** [comment]
No problem.

**Comment by noee** [comment]
Try this one.  It has the alignment stuff in it and the flat buttons (no option).  I don't know how to turn on native font rendering.  This one also has cleaned up mcws command logic.  I've only tested this with Latte, however.
[mcwsremote-v1.12.plasmoid.zip](https://github.com/noee/mcwsplasmoid/files/1944689/mcwsremote-v1.12.plasmoid.zip)

**Comment by noee** [comment]
This one should have the alignment and font enhancements.  I've tested on Latte with multiple zones.
[mcwsremote-v1.11.99.plasmoid.zip](https://github.com/noee/mcwsplasmoid/files/1946816/mcwsremote-v1.11.99.plasmoid.zip)

**Comment by KottV** [comment]
https://github.com/noee/mcwsplasmoid/pull/4#issuecomment-384255106

ok, I didn't test with multiple zones

but fonts are still to small
![default](https://user-images.githubusercontent.com/4686351/39244050-cdf249be-48d2-11e8-849a-8b3531ea4a81.png)

**Comment by KottV** [comment]
how it looks with   property int pixSize: root.height * 0.3

![default](https://user-images.githubusercontent.com/4686351/39244111-0750c172-48d3-11e8-8d91-5b96340485c9.png)

**Comment by noee** [comment]
Alright, I'll check that too, I'll add a Plasma5 panel so I can see both that and Latte.  You're sizing looks weird too, do you have the config option for sizing set to "Size to Number of Zones"?

**Comment by KottV** [comment]
no
unfortunately, it breaks positioning: 
![default](https://user-images.githubusercontent.com/4686351/39245075-07d8bf16-48d6-11e8-9e33-e39a5ea3f769.png)

**Comment by noee** [comment]
Yep, okay, I've been testing with Latte all this time and it behaves much different than standard panels when sizing and positioning.  I'll see if I can get a good compromise.

**Comment by noee** [comment]
Okay, rebase to master and reinstall the plasmoid, it should handle positioning much better now, both Plasma panels and Latte, multi and single zone.

**Comment by KottV** [comment]
Positioning is nice now, fonts better too. But buttons too small:)

**Comment by noee** [comment]
Try this one:

[mcwsremote-v1.11.99.plasmoid.zip](https://github.com/noee/mcwsplasmoid/files/1951743/mcwsremote-v1.11.99.plasmoid.zip)
