### ISSUE TITLE
Fedora 29 KDE, module "QtQuick" version 2.12 is not installed

### ISSUE THREAD

**Issue by gcarmin** [noee/mcwsplasmoid#6]
Hi - I've just installed this from the plasmas addon manager in KDE and I'm getting the following error:
Error loading QML file: file:///home/guyc/.local/share/plasma/plasmoids/org.kde.mcwsremote/contents/ui/main.qml:170:5: Type Splash unavailable
file:///home/guyc/.local/share/plasma/plasmoids/org.kde.mcwsremote/contents/ui/Splash.qml:1:1: module "QtQuick" version 2.12 is not installed
I'm using the latest update of Fedora, and the MCW version is 1.14.0.
Thanks,
Guy.

**Comment by noee** [comment]
Okay, I'll drop it back to 2.11, I'll release a new version today

**Comment by noee** [comment]
SOrry, didn't see this, but I just put a new rev that should fix it.  Thx.

**Comment by gcarmin** [comment]
Hey - Thanks - now it says:
Error loading QML file: file:///home/guyc/.local/share/plasma/plasmoids/org.kde.mcwsremote/contents/ui/main.qml:96:9: Type CompactView unavailable
file:///home/guyc/.local/share/plasma/plasmoids/org.kde.mcwsremote/contents/ui/CompactView.qml:164:17: Type Marquee unavailable
file:///home/guyc/.local/share/plasma/plasmoids/org.kde.mcwsremote/contents/ui/controls/Marquee.qml:97:5: Type FadeText unavailable
file:///home/guyc/.local/share/plasma/plasmoids/org.kde.mcwsremote/contents/ui/controls/FadeText.qml:2:1: module "QtQuick.Controls" version 2.5 is not installed

while I have:
[guyc@Gandalf29 ~]$ rpm -qa | grep -i QtQuick
qt5-qtquickcontrols-examples-5.11.3-1.fc29.x86_64
qt5-qtquickcontrols2-5.11.3-1.fc29.x86_64
qt5-qtquickcontrols-5.11.3-1.fc29.x86_64
kqtquickcharts-18.04.3-1.fc29.x86_64
qt5-qtquickcontrols2-examples-5.11.3-1.fc29.x86_64


Thanks, 
Guy.

**Comment by noee** [comment]
Try this one
[mcwsremote-v1.15.1.zip](https://github.com/noee/mcwsplasmoid/files/2798988/mcwsremote-v1.15.1.zip)

**Comment by gcarmin** [comment]
Thanks - this one is working :+1:

**Comment by noee** [comment]
Cool.  Lemme know if there's anything else.

**Comment by gcarmin** [comment]
Hey Mike,
So now for some reason - I can't control MC:
as you can see - the webui is working, and it seems that MCWS is connected
as well:
[image: image.png]

**Comment by noee** [comment]
Try going to configure, then click the MCWS host and you should see connection info in green if it can find the host.

Also, you can find the config file (/home/youruser/.local/share/plasma/plasmoids/org.kde.mcwsremote/contents/config/main.xml) and change the entry "allowDebug" to true, save and close, then restart Plasmashell (or Latte) and you can see debug messages in a window.

**Comment by gcarmin** [comment]
Well - Everything seems to be working BUT the controlling function itself.
If you want I can send you the screen-shots


[image: image.png]

----
“Only when the last tree has died,
and the last river has been poisoned,
and the last fish has been caught,
will we realize that we cannot eat money.”
(Chief Seattle)
----
may the source be with you.
-----
Sure Linux is user-friendly,
it's just picky about who its friends are.
------
Free your mind,
And your OS will follow
------
echo hvz/dbsnjoAhnbjm/dpn | perl -pe 's/./chr(ord($&)-1)/ge'

**Comment by noee** [comment]
Yeah, send them or paste them somewhere.  
Exactly what are you trying to do?    Is it in the panel view or the popup where you're having the problem.
One thing to check, go to configure/Appearance and turn off "Hide Controls".

**Comment by gcarmin** [comment]
ok -what's you email?
Mine is guy.carmin@gmail.com


----
“Only when the last tree has died,
and the last river has been poisoned,
and the last fish has been caught,
will we realize that we cannot eat money.”
(Chief Seattle)
----
may the source be with you.
-----
Sure Linux is user-friendly,
it's just picky about who its friends are.
------
Free your mind,
And your OS will follow
------
echo hvz/dbsnjoAhnbjm/dpn | perl -pe 's/./chr(ord($&)-1)/ge'

**Comment by noee** [comment]
See your email.  Try installing this one, it has the debug windows enabled.  Do you have the plasmoid installed in a plasma panel or in a latte dock panel?
[mcwsremote-v1.15.99.zip](https://github.com/noee/mcwsplasmoid/files/2803168/mcwsremote-v1.15.99.zip)

**Comment by noee** [comment]
Not sure what's going on there.  Try this one.  Remove localhost from config, then add it again and let's see what happens.  I've made a small change to the host config as well as adding the "Alive" debug so we can see what it returns.
[mcwsremote-v1.15.99.zip](https://github.com/noee/mcwsplasmoid/files/2803256/mcwsremote-v1.15.99.zip)

**Comment by gcarmin** [comment]
Hi mike,

Thank you for all of your support.
I've installed the new version and send you the screenshots to your email.
I've remove localhost and add it back
Still not working (I can't control JRive-MC.
I'm using the regular KDE pannel .
Thnaks,
----

**Comment by noee** [comment]
Here is one that bypasses the "Alive" info.  Make sure you are restarting plasmashell after you install these test versions:  plasmashell --replace &
[mcwsremote-v1.15.99-noalive.zip](https://github.com/noee/mcwsplasmoid/files/2804339/mcwsremote-v1.15.99-noalive.zip)

**Comment by gcarmin** [comment]
Hey - Sorry for the late reply - but I see the same.
I'll send you the screen shot to the email.
